locations: [
  // Outposts
  {
    name: "Ancient Spire Outpost",
    grid: "Q-17",
    region: "The Ancient Isles",
    type: "Outpost",
  },
  {
    name: "Dagger Tooth Outpost",
    grid: "M-8",
    region: "The Wilds",
    type: "Outpost",
  },
  {
    name: "Galleon's Grave Outpost",
    grid: "R-8",
    region: "The Wilds",
    type: "Outpost",
  },
  {
    name: "Golden Sands Outpost",
    grid: "D-10",
    region: "The Shores of Plenty",
    type: "Outpost",
  },
  {
    name: "Morrow's Peak Outpost",
    grid: "V-17",
    region: "The Devil's Roar",
    type: "Outpost",
  },
  {
    name: "Plunder Outpost",
    grid: "J-18",
    region: "The Ancient Isles",
    type: "Outpost",
  },
  {
    name: "Sanctuary Outpost",
    grid: "F-7",
    region: "The Shores of Plenty",
    type: "Outpost",
  },
  //Fortress
  {
    name: "Keel Haul Fort",
    grid: "C-6",
    region: "The Shores of Plenty",
    type: "fortress",
  },
  {
    name: "Hidden Spring Keep",
    grid: "I-8",
    region: "The Shores of Plenty",
    type: "fortress",
  },
  {
    name: "Sailor's Knot Stronghold",
    grid: "E-14",
    region: "The Shores of Plenty",
    type: "fortress",
  },
  {
    name: "Lost Gold Fort",
    grid: "H-17",
    region: "The Ancient Isles",
    type: "fortress",
  },
  {
    name: "Old Boot Fort",
    grid: "L-14",
    region: "The Ancient Isles",
    type: "fortress",
  },
  {
    name: "The Crow's Nest Fortress",
    grid: "O-17",
    region: "The Ancient Isles",
    type: "fortress",
  },
  {
    name: "Skull Keep",
    grid: "P-9",
    region: "The Wilds",
    type: "fortress",
  },
  {
    name: "Kraken Watchtower",
    grid: "L-6",
    region: "The Wilds",
    type: "fortress",
  },
  {
    name: "Shark Fin Camp",
    grid: "P-5",
    region: "The Wilds",
    type: "fortress",
  },
  {
    name: "Molten Sands Fortress",
    grid: "Z-11",
    region: "The Devil's Roar",
    type: "fortress",
  },
  //seapost
  {
    name: "The Spoils of Plenty Store",
    grid: "B-7",
    region: "The Shores of Plenty",
    type: "seapost",
  },
  {
    name: "The North Star Seapost",
    grid: "H-10",
    region: "The Shores of Plenty",
    type: "seapost",
  },
  {
    name: "The Finest Trading Post",
    grid: "F-17",
    region: "The Ancient Isles",
    type: "seapost",
  },
  {
    name: "Stephen's Spoils",
    grid: "L-15",
    region: "The Ancient Isles",
    type: "seapost",
  },
  {
    name: "Three Paces East Seapost",
    grid: "S-10",
    region: "The Wilds",
    type: "seapost",
  },
  {
    name: "The Wild Treasures Store",
    grid: "O-4",
    region: "The Wilds",
    type: "seapost",
  },
  {
    name: "Brian's Bazaar",
    grid: "Y-12",
    region: "The Devil's Roar",
    type: "seapost",
  },
  {
    name: "Roaring Traders",
    grid: "U-20",
    region: "The Devil's Roar",
    type: "seapost",
  },
  //Islands and Islets
  {
    name: "Barnacle Cay",
    grid: "O-15",
    region: "The Ancient Isles",
    type: "Islet",
  },
  {
    name: "Black Sand Atoll",
    grid: "O-3",
    region: "The Wilds",
    type: "Islet",
  },
  {
    name: "Black Water Enclave",
    grid: "R-5",
    region: "The Wilds",
    type: "Islet",
  },
  {
    name: "Blind Man's Lagoon",
    grid: "N-6",
    region: "The Wilds",
    type: "Islet",
  },
  {
    name: "Booty Isle",
    grid: "K-20",
    region: "The Ancient Isles",
    type: "Islet",
  },
  {
    name: "Boulder Cay",
    grid: "G-5",
    region: "The Shores of Plenty",
    type: "Islet",
  },
  {
    name: "Brimstone Rock",
    grid: "X-18",
    region: "The Devil's Roar",
    type: "Islet",
  },
  {
    name: "Castaway Isle",
    grid: "K-14",
    region: "The Ancient Isles",
    type: "Islet",
  },
  {
    name: "Chicken Isle",
    grid: "I-16",
    region: "The Ancient Isles",
    type: "Islet",
  },
  {
    name: "Cinder Islet",
    grid: "U-14",
    region: "The Devil's Roar",
    type: "Islet",
  },
  {
    name: "Cursewater Shores",
    grid: "Y-13",
    region: "The Devil's Roar",
    type: "Islet",
  },
  {
    name: "Cutlass Cay",
    grid: "M-18",
    region: "The Ancient Isles",
    type: "Islet",
  },
  {
    name: "Flame's End",
    grid: "V-19",
    region: "The Devil's Roar",
    type: "Islet",
  },
  {
    name: "Fools Lagoon",
    grid: "I-14",
    region: "The Ancient Isles",
    type: "Islet",
  },
  {
    name: "Forsaken Brink",
    grid: "U-16",
    region: "The Devil's Roar",
    type: "Islet",
  },
  {
    name: "Glowstone Cay",
    grid: "Z-18",
    region: "The Devil's Roar",
    type: "Islet",
  },
  {
    name: "Isle of Last Words",
    grid: "O-9",
    region: "The Wilds",
    type: "Islet",
  },
  {
    name: "Lagoon of Whispers",
    grid: "D-12",
    region: "The Shores of Plenty",
    type: "Islet",
  },
  {
    name: "Liar's Backbone",
    grid: "S-11",
    region: "The Wilds",
    type: "Islet",
  },
  {
    name: "Lonely Isle",
    grid: "G-8",
    region: "The Shores of Plenty",
    type: "Islet",
  },
  {
    name: "Lookout Point",
    grid: "I-20",
    region: "The Ancient Isles",
    type: "Islet",
  },
  {
    name: "Magma's Tide",
    grid: "Y-20",
    region: "The Devil's Roar",
    type: "Islet",
  },
  {
    name: "Mutineer Rock",
    grid: "N-19",
    region: "The Ancient Isles",
    type: "Islet",
  },
  {
    name: "Old Salts Atoll",
    grid: "F-18",
    region: "The Ancient Isles",
    type: "Islet",
  },
  {
    name: "Paradise Spring",
    grid: "L-17",
    region: "The Ancient Isles",
    type: "Islet",
  },
  {
    name: "Picaroon Palms",
    grid: "I-4",
    region: "The Shores of Plenty",
    type: "Islet",
  },
  {
    name: "Plunderer's Plight",
    grid: "Q-6",
    region: "The Wilds",
    type: "Islet",
  },
  {
    name: "Rapier Cay",
    grid: "D-8",
    region: "The Shores of Plenty",
    type: "Islet",
  },
  {
    name: "Roaring Sands",
    grid: "U-21",
    region: "The Devil's Roar",
    type: "Islet",
  },
  {
    name: "Rum Runner Isle",
    grid: "H-9",
    region: "The Shores of Plenty",
    type: "Islet",
  },
  {
    name: "Salty Sands",
    grid: "G-3",
    region: "The Shores of Plenty",
    type: "Islet",
  },
  {
    name: "Sandy Shallows",
    grid: "D-5",
    region: "The Shores of Plenty",
    type: "Islet",
  },
  {
    name: "Scorched Pass",
    grid: "X-11",
    region: "The Devil's Roar",
    type: "Islet",
  },
  {
    name: "Scurvy Isley",
    grid: "K-4",
    region: "The Wilds",
    type: "Islet",
  },
  {
    name: "Sea Dog's Rest",
    grid: "C-11",
    region: "The Shores of Plenty",
    type: "Islet",
  },
  {
    name: "Shark Tooth Key",
    grid: "P-13",
    region: "The Wilds",
    type: "Islet",
  },
  {
    name: "Shiver Retreat",
    grid: "Q-11",
    region: "The Wilds",
    type: "Islet",
  },
  {
    name: "Tri-Rock Isle",
    grid: "R-10",
    region: "The Wilds",
    type: "Islet",
  },
  {
    name: "Twin Groves",
    grid: "H-11",
    region: "The Shores of Plenty",
    type: "Islet",
  },
  {
    name: "Ashen Reaches",
    grid: "V-23",
    region: "The Devil's Roar",
    type: "Island",
  },
  {
    name: "Cannon Cove",
    grid: "G-10",
    region: "The Shores of Plenty",
    type: "Island",
  },
  {
    name: "Crescent Isle",
    grid: "B-9",
    region: "The Shores of Plenty",
    type: "Island",
  },
  {
    name: "Crook's Hollow",
    grid: "M-16",
    region: "The Ancient Isles",
    type: "Island",
  },
  {
    name: "Devil's Ridge",
    grid: "P-19",
    region: "The Ancient Isles",
    type: "Island",
  },
  {
    name: "Discovery Ridge",
    grid: "E-17",
    region: "The Ancient Isles",
    type: "Island",
  },
  {
    name: "Fetcher's Rest",
    grid: "V-12",
    region: "The Devil's Roar",
    type: "Island",
  },
  {
    name: "Flintlock Peninsula",
    grid: "W-14",
    region: "The Devil's Roar",
    type: "Island",
  },
  {
    name: "Kraken's Fall",
    grid: "R-12",
    region: "The Wilds",
    type: "Island",
  },
  {
    name: "Lone Cove",
    grid: "H-6",
    region: "The Shores of Plenty",
    type: "Island",
  },
  {
    name: "Marauder's Arch",
    grid: "Q-3",
    region: "The Wilds",
    type: "Island",
  },
  {
    name: "Mermaid's Hideaway",
    grid: "B-13",
    region: "The Shores of Plenty",
    type: "Island",
  },
  {
    name: "Old Faithful Isle",
    grid: "M-4",
    region: "The Wilds",
    type: "Island",
  },
  {
    name: "Plunder Valley",
    grid: "G-16",
    region: "The Ancient Isles",
    type: "Island",
  },
  {
    name: "Ruby's Fall",
    grid: "Y-16",
    region: "The Devil's Roar",
    type: "Island",
  },
  {
    name: "Sailor's Bounty",
    grid: "C-4",
    region: "The Shores of Plenty",
    type: "Island",
  },
  {
    name: "Shark Bait Cove",
    grid: "H-19",
    region: "The Ancient Isles",
    type: "Island",
  },
  {
    name: "Shipwreck Bay",
    grid: "M-10",
    region: "The Wilds",
    type: "Island",
  },
  {
    name: "Smugglers' Bay",
    grid: "F-3",
    region: "The Shores of Plenty",
    type: "Island",
  },
  {
    name: "Snake Island",
    grid: "K-16",
    region: "The Ancient Isles",
    type: "Island",
  },
  {
    name: "The Crooked Masts",
    grid: "O-11",
    region: "The Wilds",
    type: "Island",
  },
  {
    name: "The Devil's Thirst",
    grid: "W-21",
    region: "The Devil's Roar",
    type: "Island",
  },
  {
    name: "The Sunken Grove",
    grid: "P-7",
    region: "The Wilds",
    type: "Island",
  },
  {
    name: "Thieves' Haven",
    grid: "L-20",
    region: "The Ancient Isles",
    type: "Island",
  },
  {
    name: "Wanderers Refuge",
    grid: "F-12",
    region: "The Shores of Plenty",
    type: "Island",
  },
];
